version: '3.8'

services:

  db:
    container_name: kwik_ecommerce-db
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor

  app:
    container_name: kwik_ecommerce-api
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
      labels:
        - kwik_ecommerce-api:latest
      args:
        - ENV=default
    ports:
      - 8080:8080
    environment:
      APP_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: toor
    volumes:
      - ./target:/srv/target
