/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.7.3")
    api("org.springframework.data:spring-data-commons:2.7.5")
    api("org.springframework.boot:spring-boot-starter-web:2.7.3")
    api("org.springdoc:springdoc-openapi-ui:1.6.4")
    api("org.liquibase:liquibase-core:4.9.1")
    api("org.projectlombok:lombok:1.18.24")
    api("io.rest-assured:rest-assured-common:5.2.0")
    api("io.rest-assured:json-path:5.2.0")
    runtimeOnly("com.h2database:h2:2.1.214")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.3")
    testImplementation("com.tngtech.archunit:archunit-junit5:0.23.1")
    testImplementation("io.rest-assured:rest-assured:5.2.0")
    testImplementation("io.rest-assured:spring-mock-mvc:5.2.0")
}

group = "com.nocpah.kwik"
version = "0.0.1-SNAPSHOT"
description = "rules-api"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
