#!/usr/bin/env bash

types="build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"
scopes="api|common"
# Create a regex for a conventional commit.
convetional_commit_regex="^(${types})(\((${scopes})\))!?: .+$"

# Get the commit message (the parameter we're given is just the path to the
# temporary file which holds the message).
commit_message=$(cat "$1")

# Check the message, if we match, all good baby.
if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   echo -e "\e[32mCommit message meets the conventional commit standards\e[0m"
   exit 0
fi

Color_Off='\033[0m'       # Text Reset

BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

echo -e "${BRed}Commit message does not meet the conventional commit standard. ${Color_Off}

For this project you can use:
   - types: ${types}
   - scopes: ${scopes}
   
More details at: https://www.conventionalcommits.org/en/v1.0.0/#summary"
exit 1