kwik-ecommerce:
  db:
    name: ${DB_NAME:kwik_ecommerce_db__mocked}
    file: ${MOCKED_DB_FILE:./mocked}
    user: kwik
    pass: kwik

spring:
  liquibase:
    enabled: true
    contexts: mocked
    change-log: classpath:/liquibase/mock/mock.yml
    user: ${kwik-ecommerce.db.user}
    password: ${kwik-ecommerce.db.pass}

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:${kwik-ecommerce.db.file}
    username: ${kwik-ecommerce.db.user}
    password: ${kwik-ecommerce.db.pass}

  jpa:
    ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
#    root: DEBUG